export const ActionTypes = {
    USER: {
        SAVE_USER: "SAVE_USER",
        USER_UPDATE_REQUEST : "USER_UPDATE_REQUEST",
        USER_UPDATE_SUCCESS : "USER_UPDATE_SUCCESS",
        USER_UPDATE_FAIL : "USER_UPDATE_FAIL",

        USER_LOGIN_REQUEST : "USER_LOGIN_REQUEST",
        USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
        USER_LOGIN_FAIL : "USER_LOGIN_FAIL"

    },
    POST: {
        NEW_POST_FAIL: "NEW_POST_FAIL",
        NEW_POST_REQUEST: "NEW_POST_REQUEST",
        NEW_POST_SUCCESS: "NEW_POST_SUCCESS",
        CLEAR_ERRORS: "CLEAR_ERRORS"
    }
}